
const DEFAULT_COLOR = "#4D8EE9";
const DEFAULT_COLOR_SELECTED = "#2466C2";
const DEFAULT_COLOR_SEPERATOR = "#6DA1E9";

const IOS_DEFAULT_PADDING_TOP = 20;

//Touch Delay
const DEFAULT_TOUCH_DELAY = 300;

export default {
    DEFAULT_COLOR,
    DEFAULT_COLOR_SELECTED,
    DEFAULT_COLOR_SEPERATOR,
    IOS_DEFAULT_PADDING_TOP
};

