
const DEFAULT_COLOR = "#4D8EE9";
const DEFAULT_COLOR_SELECTED = "#2466C2";
const DEFAULT_COLOR_SEPERATOR = "#6DA1E9";

const IOS_DEFAULT_PADDING_TOP = 20;

//WITHOUT LOGIN
const BUTTON_TEXT_1 = "LEARN MORE"
const BUTTON_TEXT_2 = "LOGIN"
const BUTTON_TEXT_3 = "SIGN UP"

//WITH LOGIN
const BUTTON_TEXT_1_LOGIN = "LEARN MORE"
const BUTTON_TEXT_2_LOGIN = "MY ACCOUNT"
const BUTTON_TEXT_3_LOGIN = "LOGOUT"

const PARAM_IS_USER_LOGIN = "is_user_login"


//Touch Delay
const DEFAULT_TOUCH_DELAY = 300;

export default {
    DEFAULT_COLOR,
    DEFAULT_COLOR_SELECTED,
    DEFAULT_COLOR_SEPERATOR,
    IOS_DEFAULT_PADDING_TOP,
    BUTTON_TEXT_1,
    BUTTON_TEXT_2,
    BUTTON_TEXT_3,
    BUTTON_TEXT_1_LOGIN,
    BUTTON_TEXT_2_LOGIN,
    BUTTON_TEXT_3_LOGIN,
    PARAM_IS_USER_LOGIN
};

